# Generated by Django 3.2 on 2023-02-21 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Необходимо названия котегории', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Необходим индификатор категории', unique=True, verbose_name='Индификатор')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Необходимо названия жанра', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Необходим индификатор жанра', unique=True, verbose_name='Идентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Необходимо названия произведения', max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Необходимо описание', null=True, verbose_name='Описание')),
                ('year', models.IntegerField(help_text='Укажите дату выхода', verbose_name='Дата выхода')),
                ('category', models.ForeignKey(help_text='Укажите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Катигория')),
                ('genres', models.ManyToManyField(help_text='Укажите жанр', related_name='titles', to='reviews.Genre', verbose_name='Жанр')),
            ],
        ),