# Generated by Django 3.2 on 2023-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(help_text='Укажите жанр', through='reviews.GenreTitle', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
